#!/bin/bash
# Script to switch between different models easily

echo "Available models:"
echo "1. Qwen/Qwen3-8B-FP8 (default, 30.5B total/3.3B active, FP8)"
echo ""

read -p "Select model (1) or enter custom model name: " choice

case $choice in
    1)
        MODEL="Qwen/Qwen3-8B-FP8"
        ;;
    *)
        MODEL="$choice"
        ;;
esac

echo ""
echo "Switching to model: $MODEL"

# Update .env.model
cat > .env.model << EOF
# Model Configuration
# Generated by switch_model.sh at $(date)

MODEL_NAME=$MODEL
MODEL_PRECISION=fp16
EOF

# Update config/model_config.py
cat > config/model_config.py << 'EOF'
"""
Central model configuration for the DNAI project.
Change the model here to update it across the entire project.
"""

# Primary model configuration
DEFAULT_MODEL_NAME = "MODEL_PLACEHOLDER"
DEFAULT_MODEL_ARCHITECTURE = "mixture-of-experts"
DEFAULT_MODEL_LAYERS = 28  # Default, will be overridden per model
DEFAULT_MODEL_EXPERTS = 16
DEFAULT_MODEL_ACTIVE_PARAMS = "2.7B"  # Default
DEFAULT_MODEL_TOTAL_PARAMS = "14.3B"  # Default

# Model-specific settings
MODEL_CONFIGS = {
    "Qwen/Qwen3-8B-FP8": {
        "architecture": "mixture-of-experts",
        "num_layers": 48,
        "num_experts": 128,
        "activated_experts": 8,
        "active_params": "3.3B",
        "total_params": "30.5B",
        "precision": "fp8",
        "max_sequence_length": 262144,
        "requires_transformers": ">=4.51.0",
    },
}

def get_model_config(model_name: str = None):
    """Get configuration for a specific model."""
    if model_name is None:
        model_name = DEFAULT_MODEL_NAME
    
    if model_name in MODEL_CONFIGS:
        return MODEL_CONFIGS[model_name]
    
    # Return default config for unknown models
    return {
        "architecture": "unknown",
        "num_layers": 24,
        "num_experts": 1,
        "active_params": "unknown",
        "total_params": "unknown",
        "precision": "fp16",
        "max_sequence_length": 2048,
    }
EOF

# Replace placeholder with actual model
sed -i.bak "s|MODEL_PLACEHOLDER|$MODEL|g" config/model_config.py
rm -f config/model_config.py.bak

echo "✅ Model configuration updated"
echo ""
echo "To apply changes:"
echo "1. Clear cache: ./clear_cache.sh"
echo "2. Restart GPU node: systemctl restart blyan"
echo ""
echo "Or set temporarily: export MODEL_NAME=$MODEL"